"""Union-merge two versions of a data shard (used to resolve git conflicts between writers).

Two independent writers (GitHub Actions and the local launchd mirror) may both add rows to the same
monthly shard. Picking either side would silently drop the other side's rows, so conflicted shards
are merged with the *same* semantics the store uses for upserts:

- ``forecast_values``: one row per key; a present value beats a missing one, later fetch beats earlier.
- ``truth_daily``: first-final policy per (station, day, source); revisions/QC flags are unioned.
- ``daily_forecasts`` / ``scores``: fully re-derived tables — keep the newer file (by mtime), it is
  regenerated by the next ``castcheck daily`` anyway.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd
import pyarrow.parquet as pq

from .sources.base import FORECAST_VALUE_COLUMNS, FORECAST_VALUE_KEY
from .store import _FV_DTYPES, _TRUTH_DTYPES, TRUTH_COLUMNS, _apply_first_final, _cast, _upsert, _write


def merge_frames(kind: str, a: pd.DataFrame, b: pd.DataFrame) -> pd.DataFrame:
    if kind == "forecast_values":
        a, b = a[FORECAST_VALUE_COLUMNS], b[FORECAST_VALUE_COLUMNS]
        for df in (a, b):
            for c in ("init_time", "valid_time", "fetched_at"):
                df[c] = pd.to_datetime(df[c], utc=True)
        return _cast(_upsert(a, b, FORECAST_VALUE_KEY, "missing_reason"), _FV_DTYPES)
    if kind == "truth_daily":
        a, b = a[TRUTH_COLUMNS].copy(), b[TRUTH_COLUMNS].copy()
        for df in (a, b):
            df["climo_date"] = pd.to_datetime(df["climo_date"]).dt.date
            df["issuance_time"] = pd.to_datetime(df["issuance_time"], utc=True)
        return _cast(_apply_first_final(pd.concat([a, b], ignore_index=True)), _TRUTH_DTYPES)
    raise ValueError(kind)


def kind_of(path: Path) -> str:
    parts = path.as_posix()
    for k in ("forecast_values", "truth_daily", "daily_forecasts", "scores"):
        if f"/{k}/" in parts or parts.startswith(f"{k}/"):
            return k
    raise ValueError(f"unknown shard kind: {path}")


def merge_files(ours: Path, theirs: Path, out: Path) -> str:
    kind = kind_of(out)
    if kind in ("daily_forecasts", "scores"):
        newer = ours if ours.stat().st_mtime >= theirs.stat().st_mtime else theirs
        out.write_bytes(newer.read_bytes())
        return f"{out}: derived table, kept newer ({newer.name})"
    a = pq.read_table(ours).to_pandas()
    b = pq.read_table(theirs).to_pandas()
    merged = merge_frames(kind, a, b)
    _write(merged, out)
    return f"{out}: {kind} union {len(a)} + {len(b)} -> {len(merged)} rows"


def main(argv: list[str]) -> int:
    if len(argv) != 4:
        print("usage: python -m castcheck.merge <ours.parquet> <theirs.parquet> <out.parquet>", file=sys.stderr)
        return 2
    print(merge_files(Path(argv[1]), Path(argv[2]), Path(argv[3])))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
